config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :categories
  resources :foods
  resources :guests
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#home"
  get "location", to: "application#location"
  get "social_wedding", to: "application#social_wedding"
  get "menu", to: "application#menu"
  get "arrival", to: "application#arrival"
  get "volunteer", to: "application#volunteer"
  get "admin", to: "application#admin"
  get '/export_csv', to: 'guests#export_csv'
  get '/export_csv_foods', to: 'foods#export_csv'

end

app/models/guest.rb
# require 'csv'    
class Guest < ApplicationRecord
    enum status: { coming: 0, not_coming: 1 }
    require "csv"
    def self.to_csv
        attributes = %w{name status amount people}
    
        CSV.generate(headers: true) do |csv|
          csv << ["שם מלא", "מגיע?", "כמה מגיעים", "מי מגיעים"]
    
          all.each do |guest|
            csv << attributes.map{ |attr| guest.send(attr) }
          end
        end
      end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, only: %i[ index ]
  # GET /guests or /guests.json
  def index
    @guests = Guest.all
  end

  # GET /guests/1 or /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests or /guests.json
  def create
    @guest = Guest.new(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to arrival_path, notice: "תודה רבה! נשמח לראותכם/ן! גל ואביב" }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1 or /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to admin_path, notice: "Guest was successfully updated." }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1 or /guests/1.json
  def destroy
    @guest.destroy

    respond_to do |format|
      format.html { redirect_to guests_url, notice: "Guest was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def export_csv
    @guests = Guest.all
     respond_to do |format|
       format.html
       format.csv { send_data @guests.to_csv }
     end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def guest_params
      params.require(:guest).permit(:name, :status, :amount, :people, :is_sleeping)
    end
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<%= simple_form_for(@guest) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

   <div class="form-inputs">
    <%= f.input :name, label: "שם מלא", required: true %>
    <%= f.input :status, collection: [["מגיע.ה", "coming"], ["לא מגיע.ה", "not_coming"]], label: "מגיע.ה?", required: true %>
    <%= f.input :amount, label: "כמה תגיעו?", required: true %>
    <%= f.input :people, label: "שמות האורחים/ות שיגיעו איתכם/ן?" %>
    <%= f.button :submit, "שליחה" %>
  </div>

<% end %>

app/views/guests/_guest.html.erb
<tr id="<%= dom_id guest %>">
  <td>
    <%= guest.name %>
  </td>
   <td>
    <% if guest.status == "coming" %>
      מגיע
    <% else %>
      לא מגיע
    <% end %>
  </td>
   <td>
    <%= guest.amount %>
  </td>
   <td>
    <%= guest.people %>
  </td>
   <td>
    <% if guest.is_sleeping %>
      כן
    <% else %>
      לא
    <% end %>
  </td>
  <td>
    <%= link_to "עריכה", edit_guest_path(guest) %>
  </td>
  <!--
  <td>
  <%# button_to "Destroy", @guest, method: :delete %>
  </td>
  -->
</tr>

app/views/guests/edit.html.erb
<h1>עריכת אורח</h1>

<%= render "form", guest: @guest %>

<br>

app/views/guests/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Guests</h1>

<div id="guests">
<table>
  <thead>
    <th>שם האורח.ת</th>
    <th>מגיע.ה?</th>
    <th>כמה מגיעים?</th>
    <th>מי מגיע?</th>
    <th>האם נשארים לישון?</th>
  </thead>
  <tbody>
    <% @guests.each do |guest| %>
      <%= render guest %>
    <% end %>
  </tbody>
</table>
 
</div>

<%= link_to "New guest", new_guest_path %>

app/views/guests/new.html.erb
<h1>New guest</h1>

<%= render "form", guest: @guest %>

<br>

<div>
  <%= link_to "Back to guests", guests_path %>
</div>

app/views/guests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @guest %>

<div>
  <%= link_to "Edit this guest", edit_guest_path(@guest) %> |
  <%= link_to "Back to guests", guests_path %>

  <%= button_to "Destroy this guest", @guest, method: :delete %>
</div>