config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :categories
  resources :foods
  resources :guests
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#home"
  get "location", to: "application#location"
  get "social_wedding", to: "application#social_wedding"
  get "menu", to: "application#menu"
  get "arrival", to: "application#arrival"
  get "volunteer", to: "application#volunteer"
  get "admin", to: "application#admin"
  get '/export_csv', to: 'guests#export_csv'
  get '/export_csv_foods', to: 'foods#export_csv'

end

app/models/food.rb
class Food < ApplicationRecord
    belongs_to :category

    require "csv"
    def self.to_csv
        attributes = %w{category title guest_name  }
    
        CSV.generate(headers: true) do |csv|
          csv << ["קטגוריה","מנה","אורח"]
    
          all.order(:category_id).each do |food|
            csv << attributes.map do |attr|
                if attr == "category"
                    food.send(attr).title
                else
                    food.send(attr)                   
                end
            end
          end
        end
    end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[ show edit update destroy ]

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to menu_path, notice: "תודה רבה! המנה נוספה לתפריט" }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to admin_path, notice: "Food was successfully updated." }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: "Food was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def export_csv
    @foods = Food.all
     respond_to do |format|
       format.html
       format.csv { send_data @foods.to_csv }
     end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def food_params
      params.require(:food).permit(:title, :guest_name, :category_id)
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Title:</strong>
    <%= food.title %>
  </p>

  <p>
    <strong>Guest name:</strong>
    <%= food.guest_name %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= food.category %>
  </p>

</div>

app/views/foods/_form.html.erb
<%= simple_form_for(@food) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title, required: true, label: "שם המנה" %>
    <%= f.input :guest_name, required: true, label: "שם האורח.ת" %>
    <%= f.association :category, label: "קטגוריה" %>
    <%= f.button :submit, "שליחה" %>
  </div>


<% end %>

app/views/foods/edit.html.erb
<h1>עריכת מנה</h1>

<%= render "form", food: @food %>

app/views/foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Foods</h1>

<div id="foods">
  <% @foods.each do |food| %>
    <%= render food %>
    <p>
      <%= link_to "Show this food", food %>
    </p>
  <% end %>
</div>

<%= link_to "New food", new_food_path %>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>