config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :categories
  resources :foods
  resources :guests
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#home"
  get "location", to: "application#location"
  get "social_wedding", to: "application#social_wedding"
  get "menu", to: "application#menu"
  get "arrival", to: "application#arrival"
  get "volunteer", to: "application#volunteer"
  get "admin", to: "application#admin"
  get '/export_csv', to: 'guests#export_csv'
  get '/export_csv_foods', to: 'foods#export_csv'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def location
        
    end
    def menu
        @food = Food.new
        @categories = Category.all
    end
    def social_wedding
      
    end
    def arrival
        @guest = Guest.new
    end
    def volunteer
        
    end
    def admin
        redirect_to new_admin_session_path unless admin_signed_in?
        @categories = Category.all
        @guests = Guest.all
        @category = Category.new
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def heb_action_name
        actions = {
            menu: "תפריט",
            location: "מיקום",
            social_wedding: "מהי חתונה חברתית?",
            arrival: "אישור הגעה",
            volunteer: "התנדבות",

        }
        actions[action_name.to_sym]
    end
end

app/views/application/admin.html.erb
<h1>אורחים</h1>

<div id="guests" data-controller="hello">
<table id='table'>
  <thead>
    <th>שם האורח.ת</th>
    <th>מגיע.ה?</th>
    <th>כמה מגיעים?</th>
    <th>מי מגיע?</th>
    <th>האם נשארים לישון?</th>
  </thead>
  <tbody>
    <% @guests.order(:created_at).each do |guest| %>
      <%= render guest %>
    <% end %>
  </tbody>
</table>
<%= link_to( 'ייצוא אורחים' ,{ :controller => :guests, :action => :export_csv, format: 'csv'}, class: "link" ) %>
</div>

app/views/application/arrival.html.erb
<p class="guest-notice"><%= notice %></p>

<%= simple_form_for(@guest) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs guest-inputs">
    <%= f.input :name, label: "שם מלא", required: true %>
    <%# f.input :status, collection: [["מגיע.ה", "coming"], ["לא מגיע.ה", "not_coming"]], label: "מגיע.ה?", required: true %>
    <%= f.input :amount, label: "כמה תגיעו?", required: true %>
    <%= f.input :people, label: "שמות האורחים/ות שיגיעו איתכם/ן?" %>
    <% if session[:is_sleeping] == "true" %>
      <div class="checkbox">
        <input class="boolean optional check" type="checkbox" value="1" name="guest[is_sleeping]" id="guest_is_sleeping">
        <label for="check1" class="label">
          <svg viewBox="0 0 100 100" height="50" width="50">
            <rect x="30" y="20" width="50" height="50" stroke="black" fill="none" />
            <g transform="translate(0,-952.36216)" id="layer1">
              <path id="path4146" d="m 55,978 c -73,19 46,71 15,2 C 60,959 13,966 30,1007 c 12,30 61,13 46,-23" fill="none" stroke="black" stroke-width="3" class="path1" />
            </g>
          </svg> 
          <span>האם תישארו לישון?</span>
        </label>
      </div>
    <% end %>
    <%= f.button :submit, "שליחה" %>
    
  </div>
<% end %>

<%# image_tag 'star.webp', class: "bg-img relative" %>

app/views/application/home.html.erb
<% session[:is_sleeping] = "true" if params[:sleep] == "yes" && session[:is_sleeping].blank? %>
<%= image_tag 'invitation.webp', class: "invite-img" %>

<p class="invitation-description">
    אנחנו מתרגשים להזמינכם/ן לחתונה שלנו! <br>
    האירוע יתקיים בשטח פתוח, זכרו להביא נעליים נוחות!
</p>
<% if session[:is_sleeping] == "true" %>
    <p class="sleeping-description">
        היי לכם, חברים , חברות ומשפחה יקרים ויקרות שלנו!!!! 

        אם קיבלתם את הלינק הזה, זה אומר שאתם יקרים לליבנו במיוחד(!) ורצינו להזמין אתכם להשאר איתנו ללילה ולחגוג עד אור הבוקר!
        אחרי המסיבה הגדולה נשאר למדורה, שירים ונשנושים!
        ואם יש דברים נוספים ויצירתיים שתרצו להביא מעצמכן לחלק הזה של הלילה יותר מנשמח!

        הלינה תהיה על מחצלות ומזרונים תחת כיפת השמיים.
        בבוקר נאכל יחד ארוחת בוקר מפנקת ונתפזר!

        מוזמנים להביא אתכם לחלק זה של הערב משקה משמח לבב אנוש.
        מלבד זה מומלץ לארוז בתיק: 
        מצעים
        שק שינה או שמיכה דקה
        פיג'מה סקסית במיוחד 
        מברשת שיניים 
        בגדי החלפה לבוקר

        נשמח אם בנוסף לאישור הגעה לחתונה תמלאו גם האם תשארו לחגוג איתנו עד אור הבוקר בחלק השני של החגיגות❤️

        לא מצליחים להפסיק להתרגש!
        אוהבים ומצפים!
        גל ואביב
    </p>
<% end %>
<div class="grid">
    <%= link_to arrival_path do %>
       <span>אישור הגעה</span>
        <%# image_tag 'star.webp' %>
    <% end %>
    <%= link_to location_path do %>
       <span>מיקום</span>
        <%# image_tag 'wheel.webp' %>
    <% end %>
</div>

app/views/application/location.html.erb
<div class="location">
רשמו בווייז- "חוות דרך התבלינים- בית לחם הגלילית".
שימו לב, ביום חמישי הכבישים עמוסים במיוחד! מומלץ לקחת מרווח בטחון.
<%= link_to 'המיקום בוויז', "https://waze.com/ul/hsvc40wpmm", class: "link" %>
</div>
<div class="hitch-hiking">
כדי להקל על כולם בהגעה ובחזרה, ועל הדרך גם לתרום לכדור הארץ שלנו, פתחנו לוח טרמפים קל לשימוש!

באים/ות ברכב? שבצו את הרכב בטבלה, כתבו את עצמכם/ן  כאיש/ת קשר.

צריכים טרמפ? בדקו אם יש רכב שיוצא מאזורכם/ן או עובר בנקודת איסוף רלוונטית, רשמו את עצמכם/ן בטבלה וצרו קשר עם הנהג/ת כדי לוודא שאכן הנסיעה מתאימה לשניכם ויכולה לסייע לכם/ן!

נסיעה טובה ובטוחה!

<%= link_to 'לוח טרמפים', "https://docs.google.com/spreadsheets/d/1x7wIIk79Nyz5fHdz0tAoC3An3sge1RGYy_9MIzveO9k/edit?usp=sharing", class: "link" %>
</div>

<%# image_tag 'location.png', class: "bg-img relative" %>

app/views/application/menu.html.erb
<p style="color: green"><%= notice %></p>
<div class="menu-page">תודה רבה שהחלטתם/ן לקחת חלק בסעודת החתונה!
נזכיר שהחתונה טבעונית (ללא בשר, עוף, דגים, מוצרי חלב וביצים)

התפריט מחולק לקטגוריות ובהמשך העמוד תוכלו להוסיף את המטעמים שלכם/ן לפי הקטגוריה המתאימה. אנחנו ממליצים להציץ לפני זה בתפריט כדי לוודא שהמנה שחשבתם/ן להביא עדיין לא רשומה, ולראות מה עדיין חסר.
שתייה ופוקאצ'ות עלינו (:

אתם/ן מוזמנים/ות להביא מנה לפי רצונכם/ן בדומה לארוחת חג משפחתית, לא צריך לבשל ל-300 אורחים/ות.
נשמח שתביאו את המטעמים בכלי הגשה, עדיפות לרב פעמי, שיחזור אליכם נקי ומצוחצח בסוף האירוע.
במקום יהיו תנורי חימום ומקררים.

במידה והכנתם/ן מנה המכילה אלרגנים מסויימים (גלוטן, אגוזים, שומשום) או ללא סוכר נשמח שתציינו זאת.
אחרי שהוספתם/ן את המנה תוכלו לרענן את העמוד כדי לראות אותה בתוך התפריט.
תודה רבה!
במידה וקיים קושי בשליחת מנה או שאתם/ן רוצות/ים לשנות משהו מוזמנים/ות לשלוח הודעה לעומרי סרבי, טלפון: <%= link_to "0526877404", "https://api.whatsapp.com/send?phone=972526877404", class: "link" %>

</div>
<%= image_tag 'leaf2.webp', class: "bg-img" %>
<h1>
הוסיפו כאן את המנה שלכם/ן</h1>
<%= simple_form_for(@food) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title, required: true, label: "שם המנה" %>
    <%= f.input :guest_name, required: true, label: "שם האורח.ת" %>
    <%= f.association :category, label: "קטגוריה", collection: Category.where.not(title: "מנות פתיחה").where.not(title: "סלטים") %>
    <%= f.button :submit, "שליחה" %>
  </div>
<% end %>
<div class="foods">
  <% @categories.each do |category| %>
  <div class="category">
    <h1>
      <%= category.title %>
    </h1>
    <h3>
     <%= category.description %>
    </h3>
    <% category.foods.each do |food|%>
    <div class="food">
      <h2 class="title">
        <%= food.title %>
      </h2>
      <%= food.guest_name %>
    </div>
      <% end %>
  </div>
  <% end %>
</div>

app/views/application/social_wedding.html.erb
<div class="social-wedding">משפחה, חברות וחברים יקרות ויקרים!
אנחנו ממש שמחים ומתרגשות לחגוג אתכם/ן את יום חתונתנו!
כשהתחלנו לחשוב על אופי החתונה שנרצה לקיים, הבנו שנרצה אירוע שיביע חברות ועשייה משותפת ולכן בחרנו לקיים חתונה חברתית.
<strong>
מה זה אומר?
</strong>אנו מזמינים אתכם/ן לקחת חלק פעיל בהקמת החתונה ובהכנת סעודת החתונה - רוב האוכל יהיה מבוסס על הבישולים הנפלאים שלכם/ן (ללא תחושת מחוייבות).
<strong>לטובת המגוון, הסדר והארגון נשמח שתוסיפו את המנה שחשבתם/ן להכין <%= link_to 'בעמוד התפריט', menu_path, class:"link" %> ו/או שתשתבצו <%= link_to 'בטבלת השתבצויות.', volunteer_path, class:"link" %>
</strong><strong>
אז איך זה עובד?
</strong>החתונה היא טבעונית, ז"א ללא מוצרים מהחי (בשר, עוף, דגים, מוצרי חלב וביצים).
אתם/ן מוזמנים/ות להביא מנה לפי רצונכם/ן בדומה לארוחת חג משפחתית, לא צריך לבשל ל-300 אורחים/ות.
נשמח שתביאו את המטעמים בכלי הגשה, עדיפות לרב פעמי, שיחזור אליכם נקי ומצוחצח בסוף האירוע.
במקום יהיו תנורי חימום ומקררים.
מכיוון שהחתונה חברתית אנחנו מנסים להשאיר את הארגון וההקמה באווירה משפחתית וחברית. נשמח אם תרצו לקחת חלק בעיצוב, הקמה, פירוק ועוד, כמובן בהתאם לרצון וליכולת.

הכי חשוב לנו שתדעו שהנוכחות שלכם ביום שלנו היא הדבר הכי חשוב והכי משמח עבורנו!
אפשר להביא מתנות או כסף לפי היכולת והרצון אבל לא מתוך תחושת מחוייבות לכסות עלויות.
נשמח מאוד לקבל ברכות, הבעות חיבה וחיבוקים חמים (:
לכל שאלה ובירור אפשר לדבר איתנו. 

מצפים ומתרגשות לראותכם/ן,
יונתן ונעה
</div>

<%= image_tag 'leaf.webp', class: "bg-img" %>

app/views/application/volunteer.html.erb
<div class="volunteer">תודה רבה שהחלטתם/ן לקחת חלק בהקמת החתונה!
מכיוון שהחתונה חברתית אנחנו מנסים להשאיר את הארגון וההקמה באווירה משפחתית וחברית. נשמח אם תרצו לקחת חלק בעיצוב, הקמה, פירוק ועוד, כמובן בהתאם לרצון וליכולת.
<%= link_to 'בטבלה', "https://docs.google.com/spreadsheets/d/1wAqIzxQltp-btkjoOIaUv-ujRphiZt1NypbouD2Wjfk/edit?usp=sharing", class:"link" %> יש משימה, הזמנים בהם היא מתבצעת ותיאור כללי של המשימה, תוכלו גם לראות מי כבר משובץ/ת.


<%= link_to 'הטבלה', "https://docs.google.com/spreadsheets/d/1wAqIzxQltp-btkjoOIaUv-ujRphiZt1NypbouD2Wjfk/edit?usp=sharing", class:"volunteer-table" %>

תודה רבה!

</div>

<%= image_tag 'clam.webp', class: "bg-img" %>