config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :categories
  resources :foods
  resources :guests
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#home"
  get "location", to: "application#location"
  get "social_wedding", to: "application#social_wedding"
  get "menu", to: "application#menu"
  get "arrival", to: "application#arrival"
  get "volunteer", to: "application#volunteer"
  get "admin", to: "application#admin"
  get '/export_csv', to: 'guests#export_csv'
  get '/export_csv_foods', to: 'foods#export_csv'

end

app/views/layouts/_nav.html.erb
<nav data-controller="nav">
    <div class="menu">
    <h1><%= link_to 'אביב וגלפי מתחתנים',root_path %></h1>
        <button class="hamburger hamburger--squeeze" type="button" data-action="nav#menu" data-nav-target="btn">
            <span class="hamburger-box">
                <span class="hamburger-inner"></span>
            </span>
        </button>
    </div>

        <ul role="list" data-nav-target="list">
            <li><%= link_to 'דף הבית',root_path, class: "#{"active" if action_name == "home"}" %> </li>
            <li><%= link_to 'אישור הגעה', arrival_path, class: "#{"active" if action_name == "arrival"}" %></li>
            <li><%= link_to 'מיקום', location_path, class: "#{"active" if action_name == "location"}" %></li>

            <% if admin_signed_in? %>
              <li><%= link_to 'דף ניהול', admin_path %></li>
              <!--
              <li><%= link_to 'התנתקות', destroy_admin_session_path, method: :delete %></li>
              -->
            <% end %>
        </ul>
</nav>
<% if heb_action_name.present? %>
    <h1 class="page-title">
        <%= heb_action_name %>
    </h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html dir=rtl lang=he>
  <head>
    <title>אביב וגל מתחתניםות</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Assistant&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    

  </head>

  <body>
    <%= render 'layouts/nav' %>
    <main class="<%= 'home' if action_name == "home" %>">
      <%= yield %>
    </main>
  </body>
</html>